name: Abrir archivo Python

on:
  push:
    branches:
      - main

jobs:
  open-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script Python
      run: python .github/workflows/Desaparecidos.py
