name: Data mining
on:
  schedule:
    - cron: "* * * * *"
   
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Run a Python script 
      - run: python .github/workflows/Desaparecidos.py
