name: Data mining

on:
  schedule:
    - cron: "* * * * *"
   
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Run a Python script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install <nombre_del_paquete>  # Si tienes dependencias adicionales, agrégalas aquí
      - name: Run the Python script
        run: python Desaparecidos.py

