name: Data mining

on:
  schedule:
    - cron: "* * * * *"
   
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #run: |
          #python -m pip install --upgrade pip
          #pip install <nombre_del_paquete>  
      - name: Run the Python script
        run: python .github/workflows/Desaparecidos.py

