name: Abrir archivo Python

on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script Python
        run: python .github/workflows/Desaparecidos.py
      - name: Push a main
        run: |
             git config --local user.email "email@gmail.com"
             git config --local user.name "username"
             git add *
             git commit -m "Actualizacion"
             git push origin main
